(define (problem pb2)
  (:domain dwr2)
  (:objects
    r1 r2 - robot
    l1 l2 l3 l4 l5 l6 l7 - location
    k1 k2 - crane
    p1 q1 p2 p3 p4 p5 p6 p7 - pile
    ca cb cc cd ce cf pallet - container
  )
  (:init
    (adjacent l1 l2) (adjacent l2 l1)
    (adjacent l1 l3) (adjacent l3 l1)
    (adjacent l1 l4) (adjacent l4 l1)
    (adjacent l2 l3) (adjacent l3 l2)
    (adjacent l4 l3) (adjacent l3 l4)
    (adjacent l3 l5) (adjacent l5 l3)
    (adjacent l5 l6) (adjacent l6 l5)
    (adjacent l5 l7) (adjacent l7 l5)
    ; (adjacent l5 l8) (adjacent l8 l5)
    (adjacent l6 l7) (adjacent l7 l6)
    ; (adjacent l7 l12) (adjacent l12 l7)
    ; (adjacent l8 l9) (adjacent l9 l8)
    ; (adjacent l9 l10) (adjacent l10 l9)
    ; (adjacent l10 l11) (adjacent l11 l10)
    ; (adjacent l11 l12) (adjacent l12 l11)
    ; (adjacent l11 l13) (adjacent l13 l11)
    ; (adjacent l11 l14) (adjacent l14 l11)
    ; (adjacent l12 l13) (adjacent l13 l12)
    ; (adjacent l13 l14) (adjacent l14 l13)
    ; (adjacent l14 l15) (adjacent l15 l14)

    (attached p1 l1) (attached q1 l1)
    (attached p2 l2) (attached q2 l2)
    (attached p3 l3)
    (attached p4 l4)
    (attached p5 l5)
    (attached p6 l6)
    (attached p7 l7)
    ; (attached p8 l8)
    ; (attached p9 l9)
    ; (attached p10 l10)
    ; (attached p11 l11)
    ; (attached p12 l12)
    ; (attached p13 l13)
    ; (attached p14 l14)
    ; (attached p15 l15)

    (belong k1 r1)
    (belong k2 r2)
    ; (belong k3 r3)

    (in ca p1) (in cb p1) (in cc p1)
    (in cd q1) (in ce q1) (in cf q1)
    (top cc p1) (on cc cb) (on cb ca) (on ca pallet)
    (top cf q1) (on cf ce) (on ce cd) (on cd pallet)
    (top pallet p2)
    ; (top pallet q2)
    (top pallet p3)
    (top pallet p4)
    (top pallet p5)
    (top pallet p6)
    (top pallet p7)
    ; (top pallet p8)
    ; (top pallet p9)
    ; (top pallet p10)
    ; (top pallet p11)
    ; (top pallet p12)
    ; (top pallet p13)
    ; (top pallet p14)
    ; (top pallet p15)

    (at r1 l1)
    (unloaded r1)
    (occupied l1)

    (at r2 l3)
    (unloaded r2)
    (occupied l3)

    ; (at r3 l7)
    ; (unloaded r3)
    ; (occupied l7)

    (empty k1)
    (empty k2)
    ; (empty k3)

    (equal ca ca) (equal cb cb) (equal cc cc) (equal cd cd) (equal ce ce) (equal cf cf) (equal pallet pallet)
  )
  (:goal (and (in cd p7) (in ce p7) (in cf p7) ))
)